HMRequests={getElements:function(d,c){var b;b=("SELECT DISTINCT ElementCode,Element_Name"+c+" FROM vData_HungerMap_AllAreas WHERE ItemCode IN ("+d+")  ORDER BY ElementCode DESC").replace(/\n/g," ");var e={},g={limit:null};g.query=b;g.frequency="NONE";e.datasource=HM_CONFIG.DATASOURCE;e.json=JSON.stringify(g);e.thousandSeparator=",";e.decimalSeparator=".";b=new RequestHandler;b.open("POST",HM_CONFIG.WDS_BASE_URL+"/rest/table/json");b.setContentType("application/x-www-form-urlencoded");b.onload(function(){var b=
this.responseText;"string"==typeof b&&(b=$.parseJSON(b));for(var a=0;a<b.length;a++){var e=$.extend(!0,{},HM.l);HM.layers.push(e);HM.layersHashMap[a]=b[a][0];HMRequests.loadMenu(a,b,e);0==a?HMRequests.getValues(e,d,b[a][0],c,!0,null):HMRequests.getValues(e,d,b[a][0],c,!1,null)}});b.send(FM.Util.parseLayerRequest(e))},loadMenu:function(d,c,b){$("#hm-timeline-"+d).click({id:d},function(b){HM.switchLayer(b.data.id)})},getValues:function(d,c,b,e,g,h){b=("SELECT AreaCode, Value FROM vData_HungerMap_AllAreas WHERE ElementCode IN ("+
b+") AND ItemCode IN ("+c+")  AND Value IS NOT NULL ").replace(/\n/g," ");c={};e={limit:null};e.query=b;e.frequency="NONE";c.datasource=HM_CONFIG.DATASOURCE;c.json=JSON.stringify(e);c.thousandSeparator=",";c.decimalSeparator=".";b=new RequestHandler;b.open("POST",HM_CONFIG.WDS_BASE_URL+"/rest/table/json");b.setContentType("application/x-www-form-urlencoded");b.onload(function(){var a=this.responseText;"string"==typeof a&&(a=$.parseJSON(a));for(var b=[],c=0;c<a.length;c++){var e={};e[a[c][0]]=a[c][1];
b.push(e)}a=JSON.stringify(b);d.layer.joindata=a;g?d.createShadeLayerRequestCached(null,!0):d.createShadeLayerRequestCached(null,!1)});b.send(FM.Util.parseLayerRequest(c))},firstLoadLayer:function(d){d.createShadeLayerRequestCached(!0)},countryGFI:function(d,c,b,e,g){b.lat.toFixed(3);b.lng.toFixed(3);var h=e.getBounds(),a=e.options.crs.project(h.getSouthWest()),h=e.options.crs.project(h.getNorthEast()),a=a.x+","+a.y+","+h.x+","+h.y,h=e.getSize().x,l=e.getSize().y,k=e.layerPointToContainerPoint(c).x;
c=e.layerPointToContainerPoint(c).y;k=new Number(k);k=k.toFixed(0);c=new Number(c);c=c.toFixed(0);var f="http://"+FM.CONFIG.BASEURL_MAPS+FM.CONFIG.MAP_SERVICE_GFI_STANDARD,f=f+"?SERVICE=WMS&VERSION=1.1.1",f=f+"&REQUEST=GetFeatureInfo",f=f+("&BBOX="+a),f=f+("&HEIGHT="+l),f=f+("&WIDTH="+h+"&FORMAT=image/png"),f=f+"&INFO_FORMAT=text/html",f=f+("&X="+k+"&Y="+c);""!=d&&null!=d&&(f+="&LAYERS="+d.layer.layername,f+="&QUERY_LAYERS="+d.layer.layername,f+="&STYLES=",f+="&SRS="+d.layer.srs,f+="&urlWMS="+d.layer.urlWMS,
HMRequests.getFeatureInfoJoinRequest(e,f,"GET",null,b,g))},getFeatureInfoJoinRequest:function(d,c,b,e,g,h){var a=new RequestHandler;a.open(b,c);a.setContentType("application/x-www-form-urlencoded");a.onload(function(){var a=this.responseText;null!=a&&$(a).find("value").each(function(){var a=$(this).find("columnname").text(),b=$(this).find("columnvalue").text();a==h&&(a=parseInt(b).toString(),HMRequests.getCountryDetails(d,HM_CONFIG.ITEMCODE,HM.layersHashMap[HM.selectedLayerIndex],a,HM.layerLang,g))})});
e?a.send(FM.Util.parseLayerRequest(e)):a.send()},getCountryDetails:function(d,c,b,e,g,h){c=("SELECT Area_Name"+g+",Item_Name"+g+",Element_Name"+g+",Value,Unit_Name"+g+" FROM vData_HungerMap_AllAreas  WHERE ElementCode IN ("+b+") AND ItemCode IN ("+c+")  AND AreaCode IN ("+e+")  AND Value IS NOT NULL ").replace(/\n/g," ");d={};b={limit:null};b.query=c;b.frequency="NONE";d.datasource=HM_CONFIG.DATASOURCE;d.json=JSON.stringify(b);d.thousandSeparator=",";d.decimalSeparator=".";c=new RequestHandler;c.open("POST",
HM_CONFIG.WDS_BASE_URL+"/rest/table/json");c.setContentType("application/x-www-form-urlencoded");c.onload(function(){var a=this.responseText;if(null!=a&&"[]"!=a){"string"==typeof a&&(a=$.parseJSON(a));HM.highlightCountry(e);HM.selectedCountryCode=e;var b=parseFloat(a[0][3]).toFixed(1),c=Math.floor(b),d=+b.toString().replace(/^[^\.]+/,"0"),d=HMRequests.replaceAll(d.toString(),"0","");$("#hm-areaname").html("");$("#hm-value").html("");$("#hm-valuedecimal").html("");$("#hm-unitname").html("");$("#hm-itemname").html("");
$("#hm-elementname").html("");if(-1>=b)$("#hm-circle").show(),$("#hm-elementaname").show(),$("#hm-missingdata").hide(),$("#hm-areaname").html(a[0][0]),$("#hm-value").html("<5"),$("#hm-unitname").html("%"),$("#hm-elementname").html(a[0][1]),$("#hm-valuecircle").removeAttr("class"),$("#hm-valuecircle").attr("class","hm-circle hm-bgcolor-1"),$("#hm-value").removeAttr("class"),$("#hm-value").attr("class","percent hm-color-1"),$("#hm-unitname").removeAttr("class"),$("#hm-unitname").attr("class","percent hm-color-1");
else if(0>=b){$("#hm-circle").hide();$("#hm-elementaname").hide();$("#hm-missingdata").show();$("#hm-areaname").html(a[0][0]);switch(HM.mapLang){case "FR":$("#hm-missingdata").html("Donn\u00e9es manquantes ou insuffisantes");break;case "ES":$("#hm-missingdata").html("Informaci\u00f3n ausente o insuficiente");break;default:$("#hm-missingdata").html("Missing or insufficient data")}$("#hm-valuecircle").removeAttr("class");$("#hm-value").removeAttr("class");$("#hm-value").attr("class","percent hm-color-0");
$("#hm-valuedecimal").removeAttr("class");$("#hm-valuedecimal").attr("class","percent hm-color-0");$("#hm-unitname").removeAttr("class");$("#hm-unitname").attr("class","percent hm-color-0")}else{$("#hm-circle").show();$("#hm-elementaname").show();$("#hm-missingdata").hide();$("#hm-areaname").html(a[0][0]);$("#hm-value").html(c);$("#hm-valuedecimal").html(d);$("#hm-unitname").html(a[0][4]);$("#hm-itemname").html(a[0][2]);$("#hm-elementname").html(a[0][1]);for(c=a=0;c<HM.rangesHM.length&&!(b<=HM.rangesHM[c]);c++)a++;
$("#hm-valuecircle").removeAttr("class");$("#hm-valuecircle").attr("class","hm-circle hm-bgcolor-"+a);$("#hm-value").removeAttr("class");$("#hm-value").attr("class","percent hm-color-"+a);$("#hm-valuedecimal").removeAttr("class");$("#hm-valuedecimal").attr("class","percent hm-color-"+a);$("#hm-unitname").removeAttr("class");$("#hm-unitname").attr("class","percent hm-color-"+a)}}});d?c.send(FM.Util.parseLayerRequest(d)):c.send()},replaceAll:function(d,c,b){for(var e=d.indexOf(c);-1!=e;)d=d.replace(c,
b),e=d.indexOf(c);return d}};